//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcss.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCT_USER_ROLE
    {
        public long ID { get; set; }
        public long SRL_ID { get; set; }
        public long USER_ID { get; set; }
    
        public virtual NCT_SYSTEM_ROLE NCT_SYSTEM_ROLE { get; set; }
        public virtual NCT_USER NCT_USER { get; set; }
    }
}
