//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcss.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCT_USER
    {
        public NCT_USER()
        {
            this.NCT_USER_ROLE = new HashSet<NCT_USER_ROLE>();
        }
    
        public long ID { get; set; }
        public string USER_NAME { get; set; }
        public string PASS { get; set; }
        public string EMAIL { get; set; }
        public short IS_ACTIVE { get; set; }
        public string LOGIN { get; set; }
    
        public virtual ICollection<NCT_USER_ROLE> NCT_USER_ROLE { get; set; }
    }
}
